version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
    - ./app:/app
    command: >
      sh -c "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=idresgait
      - DB_USER=gaituser
      - DB_PASSS=gaituserpass
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=idresgait
      - POSTGRES_USER=gaituser
      - POSTGRES_PASSWORD=gaituserpass