# Generated by Django 3.2 on 2021-04-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
